format = """
[](#5C8374)\
[   ](bg:#5C8374 fg:#ffffff)\
[](bg:#5B9A8B fg:#5C8374)\
$directory\
[](fg:#5B9A8B bg:#93B1A6)\
$git_branch\
$git_status\
$git_state\
[](fg:#93B1A6 bg:#c9c9c9)\
$nodejs\
$rust\
$golang\
$php\
$python\
$docker_context\
[](fg:#c9c9c9 bg:#6c7a89)\
$time\
[ ](fg:#6c7a89)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#5B9A8B"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#93B1A6"
format = '[[ $symbol $branch ](fg:#000000 bg:#93B1A6)]($style)'

[git_status]
style = "bg:#93B1A6"
format = '[[($all_status$ahead_behind )](fg:#000000 bg:#93B1A6)]($style)'
conflicted = "="
ahead =	"⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count} "
stashed = "$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
disabled = false

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[status]
format = "[$symbol$status]($style)"
symbol = "✖"
style = "bold red"
disabled = true

[docker_context]
symbol = " "
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[nodejs]
symbol = ""
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[rust]
symbol = ""
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[golang]
symbol = ""
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[php]
symbol = ""
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[python]
symbol = " "
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6c7a89"
format = '[[  $time ](fg:#ffffff bg:#6c7a89)]($style)'
