format = """
[░▒▓](#a3aed2)\
[ 󰣇 ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#a3aed2)\
$git_branch\
$git_status\
[](fg:#a3aed2 bg:#c9c9c9)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#c9c9c9 bg:#6c7a89)\
$time\
[ ](fg:#6c7a89)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#a3aed2"
format = '[[ $symbol $branch ](fg:#000000 bg:#a3aed2)]($style)'

[git_status]
style = "bg:#a3aed2"
format = '[[($all_status$ahead_behind )](fg:#000000 bg:#a3aed2)]($style)'

[nodejs]
symbol = ""
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[rust]
symbol = ""
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[golang]
symbol = ""
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[php]
symbol = ""
style = "bg:#c9c9c9"
format = '[[ $symbol ($version) ](fg:#000000 bg:#c9c9c9)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6c7a89"
format = '[[  $time ](fg:#ffffff bg:#6c7a89)]($style)'
